#!/usr/bin/env bash

set -e

source functions.sh

# Read configuration variable file if it is present
[ -r "./settings.conf" ] && . ./settings.conf

UNIQ=`date | sha1sum | cut -c 1-7`
ISO=`find ./iso/ubuntu-18.04* | head -n1`

VMS_ROOT="${HOME}/VirtualBox VMs"
VM="Ubuntu-`echo ${ISO} | cut -d "-" -f 2-3`-${UNIQ}"
VM_HDD="${VMS_ROOT}/${VM}/${VM}"
VM_HDD_FILE="${VM_HDD}.vdi"

shout "Setting up"

rm -f ./*.img
rm -f ./*.iso

# Some dependency checks
directory_exists "${VMS_ROOT}" "Cannot find VirtualBox VM directory ${VMS_ROOT}"
file_exists "${ISO}" "Cannot find iso ${ISO}"
is_runnable "vboxmanage" "Cannot find/run vboxmanage"
is_runnable "mkisofs" "Cannot find/run mkisofs"
is_runnable "7z" "Cannot find/run 7z"
is_runnable "sha1sum" "Cannot find/run sha1sum"
is_runnable "grub-mkimage" "Cannot find/run grub-mkimage"

mkdir -p "./tmp/"

LODEVICE=`losetup -f`

shout "Using loopback device ${LODEVICE}"

# 4GB image
dd if=/dev/zero of=./${VM}-unattended.img bs=1G count=4
sudo losetup ${LODEVICE} ./${VM}-unattended.img
sudo mkfs.vfat -S 4096 ${LODEVICE}
sudo mount -ouser,umask=0000 ${LODEVICE} ./tmp
sudo chmod 0777 ./tmp

shout "Copying ${ISO}"

cp ${ISO} ./tmp/install.iso

shout "Copying configuration"

cp ./custom.seed ./tmp

mkdir -p ./tmp/efi/boot
cp ./grub.cfg ./tmp/efi/boot
pushd ./tmp/efi/boot

grub-mkimage -o bootx64.efi -p /efi/boot -O x86_64-efi \
 fat iso9660 part_gpt part_msdos \
 normal boot linux configfile loopback chain \
 efifwsetup efi_gop efi_uga \
 ls search search_label search_fs_uuid search_fs_file \
 gfxterm gfxterm_background gfxterm_menu test all_video loadenv \
 exfat ext2 ntfs btrfs hfsplus udf

popd

shout "Cleanup"

sudo umount ./tmp
sudo losetup -d ${LODEVICE}

shout "Done?"

shout "Booting VM to start install"

VBoxManage createvm --name "${VM}" --register
VBoxManage modifyvm "${VM}" --ostype Ubuntu_64 --memory 8192 --vram 64 --rtcuseutc on --ioapic on \
           --clipboard bidirectional --cpus 2 --firmware efi64 --usbehci on

# Primary disk
VBoxManage storagectl "${VM}" --name sata0 --add sata --portcount 1
VBoxManage createhd --filename "${VM_HDD_FILE}" --size 40960
VBoxManage storageattach "${VM}" --storagectl sata0 --port 0 --type hdd --medium "${VM_HDD_FILE}"

# Rest of config
VBoxManage modifyvm "${VM}" --nic1 nat

VBoxManage storagectl "${VM}" --name ide0 --add ide
mv ./${VM}-unattended.img ./${VM}-unattended.iso
VBoxManage storageattach "${VM}" --storagectl ide0 --device 0 --port 0 --type dvddrive --medium ./${VM}-unattended.iso

VBoxManage startvm --type=gui "${VM}"
